# fly.toml app configuration file generated for enlightened-fellows-discord-bot on 2025-08-26T20:10:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'enlightened-fellows-discord-bot'
primary_region = 'sin'

[experimental]

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  NODE_ENV = 'production'

[processes]
  app = 'node dist/index.js'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
