# fly.toml app configuration file generated for enlightened-fellows-discord-bot on 2025-08-26T12:40:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'enlightened-fellows-discord-bot'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
