-- Data-only migration: empty the MH Wilds catalog so the scraper can re-ingest
-- it from scratch. 0006 removed the stale set/group rows from `skill`, which
-- unblocked `GET /api/mh-wilds/skills`, but the catalog is still a pre-migration
-- snapshot (last successful ingest: scraper:boot, 2026-06-14) that several
-- schema migrations landed on top of without ever backfilling data:
--
--   * `bonus` / `bonus_threshold` / `armor_bonus` (ADR-0011) are empty.
--   * `skill.icon` was added but is NULL on every row.
--   * `skill.type` is 'armor' on every row; upstream types many as 'weapon'.
--   * `decoration_skill` replaced `decoration.skill_id` and is empty.
--   * 137 skills are present where upstream now publishes 179.
--
-- The scraper cannot repair this itself: `reconcileCatalog` is insert-only
-- (ADR-0007) and reports any existing name whose fields differ as a conflict,
-- which rejects the entire scrape — the last two `scraper:manual` runs failed
-- with 1212 conflicts, every one of them 'skill definition changed'. Emptying
-- the tables makes every identity new, so reconciliation has nothing to
-- conflict on. Re-populating is the scraper's job, not this migration's: run
-- `POST /api/mh-wilds/fetch-armors` once this has been applied.
--
-- Catalog UUIDs are regenerated by that scrape. This is only safe while nothing
-- user-owned references them — `custom_talisman` is the one table that does
-- (ADR-0007), so refuse rather than silently orphan it. `saved_build` holds a
-- self-contained composition snapshot with no catalog FKs (ADR-0005).
DO $$
DECLARE talismans int;
BEGIN
  SELECT count(*) INTO talismans FROM custom_talisman;

  IF talismans > 0 THEN
    RAISE EXCEPTION
      'Refusing to reset the catalog: % custom talisman(s) reference catalog skill ids. Re-ingesting would orphan them — migrate those references first.',
      talismans;
  END IF;
END $$;--> statement-breakpoint
-- CASCADE covers the join tables, but they are named explicitly so the intent
-- is auditable and a future FK cannot silently widen this statement's blast
-- radius. No sequences to reset — every catalog id is a text UUID.
TRUNCATE TABLE
  "armor_skill",
  "armor_bonus",
  "decoration_skill",
  "bonus_threshold",
  "armor",
  "decoration",
  "bonus",
  "skill"
CASCADE;
